export const pinsData = [
  {
    id: "1",
    image: "https://picsum.photos/seed/pin1/600/800",
    title: "Modern interior",
    description: "Cozy minimalistic living room",
    avatar: "https://i.pravatar.cc/150?img=1",
    author: "Anna",
    hashtags: ["interior", "design", "home"],
    views: 1240,
    likes: 185,
  },
  {
    id: "2",
    image: "https://picsum.photos/seed/pin2/600/900",
    title: "Travel inspiration",
    description: "Beautiful place for your next trip",
    avatar: "https://i.pravatar.cc/150?img=2",
    author: "Alex",
    hashtags: ["travel", "nature", "summer"],
    views: 3580,
    likes: 420,
  },
  {
    id: "3",
    image: "https://picsum.photos/seed/pin3/600/700",
    title: "Street fashion",
    description: "Casual outfit inspiration",
    avatar: "https://i.pravatar.cc/150?img=3",
    author: "Kate",
    hashtags: ["fashion", "style", "outfit"],
    views: 890,
    likes: 97,
  },
  {
    id: "4",
    image: "https://picsum.photos/seed/pin4/600/850",
    title: "Morning coffee",
    description: "Perfect coffee setup for a slow morning",
    avatar: "https://i.pravatar.cc/150?img=4",
    author: "Daniel",
    hashtags: ["coffee", "morning", "lifestyle"],
    views: 1760,
    likes: 243,
  },
  {
    id: "5",
    image: "https://picsum.photos/seed/pin5/600/750",
    title: "Healthy breakfast",
    description: "Fresh and colorful breakfast ideas",
    avatar: "https://i.pravatar.cc/150?img=5",
    author: "Sophie",
    hashtags: ["food", "healthy", "breakfast"],
    views: 2140,
    likes: 315,
  },
  {
    id: "6",
    image: "https://picsum.photos/seed/pin6/600/950",
    title: "Mountain escape",
    description: "Amazing views from the mountain trail",
    avatar: "https://i.pravatar.cc/150?img=6",
    author: "Michael",
    hashtags: ["mountains", "travel", "adventure"],
    views: 4620,
    likes: 578,
  },
  {
    id: "7",
    image: "https://picsum.photos/seed/pin7/600/800",
    title: "Creative workspace",
    description: "Minimal desk setup for productive work",
    avatar: "https://i.pravatar.cc/150?img=7",
    author: "Emma",
    hashtags: ["workspace", "productivity", "design"],
    views: 1950,
    likes: 268,
  },
  {
    id: "8",
    image: "https://picsum.photos/seed/pin8/600/720",
    title: "City lights",
    description: "Night atmosphere in the heart of the city",
    avatar: "https://i.pravatar.cc/150?img=8",
    author: "Chris",
    hashtags: ["city", "night", "photography"],
    views: 3270,
    likes: 394,
  },
];
